--- #YAML:1.0
name:                Acme-CPANAuthors-British
version:             0.01
abstract:            We are British CPAN authors
license:             perl
author:              
    - Barbie <barbie@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Acme::CPANAuthors:             0.04
    Test::More:                    0.70
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
